# Generated by Django 4.1.3 on 2022-11-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Bodypart', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
            ],
        ),
    ]
